<?xml version="1.0" encoding="utf-8"?>
<NYCDOT-TrafficSpeed xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="transcomLinks">
<TrafficSpeedData linkId="4616337" linkName="11th ave n ganservoort - 12th ave @ 40th st" linkBorough="Manhattan" linkOwner="NYC_DOT_LIC" linkPolyline="}btwFx|ubMsD_AgJcAcR{ByJ_AsBFiEbByCXaFuAkLiDsTaNsPoKmCmB" linkPolylineLvl="BBBBBBBBBBBBB" linkSpeed="21.13" linkTravelTime="247" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616325" linkName="11th ave s ganservoort - west st @ spring st" linkBorough="Manhattan" linkOwner="NYC_DOT_LIC" linkPolyline="y{swFvavbMjANlGSvQn@fa@fBhQdA" linkPolylineLvl="BBBBBB" linkSpeed="24.23" linkTravelTime="134" linkStatus="0" linkTimeStamp="11/8/2016 13:53:36" />
<TrafficSpeedData linkId="4616324" linkName="12th ave @ 45th - 11 ave ganservoort st" linkBorough="Manhattan" linkOwner="NYC_DOT_LIC" linkPolyline="mtxwF|}sbMl@^~GpK|LrIbLlH??lK~G|FtD`C~@}@WdWnGdKmC|k@~G`CRzElC" linkPolylineLvl="BBBBBBBBBBBBBBB" linkSpeed="14.91" linkTravelTime="412" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616338" linkName="12th Ave N 40th - 57th St" linkBorough="Manhattan" linkOwner="NYC_DOT_LIC" linkPolyline="kaxwFjptbM{GuFuFgIwHsFmJqG_OwJcCw@qE[cBc@" linkPolylineLvl="BBBBBBBBB" linkSpeed="16.78" linkTravelTime="188" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616323" linkName="12th Ave S 57th St - 45th St" linkBorough="Manhattan" linkOwner="NYC_DOT_LIC" linkPolyline="kezwFf`sbMv@TxAVnDZe@Gz@J~@Xf@VlEnC??~KpH??vCpB??zEbD??dC`B" linkPolylineLvl="BBBBBBBBBBBBBBBBB" linkSpeed="6.84" linkTravelTime="308" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616279" linkName="278 E BRUNSWICK AVENUE - SIE E SOUTH AVENUE" linkBorough="Staten Island" linkOwner="NYC_DOT_LIC" linkPolyline="aaawFdw}cMZyDKgMd@mF`GsN`FwJtAkCnBgDnGwKrBuD|DgJpFgMbGiNlQoa@hCgGnDwHbHeOpH}OzI{KnHmIzCaFpCaLlBsV" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="49.71" linkTravelTime="217" linkStatus="0" linkTimeStamp="12/3/2014 12:26:11" />
<TrafficSpeedData linkId="4616280" linkName="278 E BRUNSWICK AVENUE - WSE S SOUTH AVENUE" linkBorough="Staten Island" linkOwner="NYC_DOT_LIC" linkPolyline="_o}vFxxvcMlF}ClEk@bEI|F|@vF|AtEv@jJ`Cfr@j]zPbKzPvQ" linkPolylineLvl="BBBBBBBBBBB" linkSpeed="37.9" linkTravelTime="315" linkStatus="0" linkTimeStamp="12/3/2014 12:20:11" />
<TrafficSpeedData linkId="4616281" linkName="440 N FRANCIS STREET - WSE N TYRELLAN AVE" linkBorough="Staten Island" linkOwner="NYC_DOT_LIC" linkPolyline="_djvF|badMP|IV`GXhY`Ajf@l@pX\zOp@`NTxL?nDmApXe@bJeBxXg@jFsDtO" linkPolylineLvl="BBBBBBBBBBBBBBB" linkSpeed="8.08" linkTravelTime="1013" linkStatus="0" linkTimeStamp="11/2/2016 12:30:30" />
<TrafficSpeedData linkId="4456502" linkName="BBT E Manhattan Portal - Toll Plaza" linkBorough="Manhattan" linkOwner="MTA Bridges &amp; Tunnels" linkPolyline="mmmwFx`wbMxDt@rAb@rFv@jCNbJOfEaAre@yMft@y_@`K}EjHcC`EkCnGgF" linkPolylineLvl="BBBBBBBBBBBBB" linkSpeed="26.72" linkTravelTime="236" linkStatus="0" linkTimeStamp="11/14/2016 17:12:40" />
<TrafficSpeedData linkId="4616344" linkName="BBT Manhattan Portal inbound - West St N Watts St" linkBorough="Manhattan" linkOwner="NYC_DOT_LIC" linkPolyline="etmwFldwbMqASqCu@qBm@iCu@gCQcC[qDm@yDq@qAUw@WcAm@wAOu@GiBi@yDk@cEq@mDg@mDg@uDg@wEm@{Dc@mFo@}Fs@" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="13.05" linkTravelTime="422" linkStatus="0" linkTimeStamp="12/8/2015 15:24:35" />
<TrafficSpeedData linkId="4616345" linkName="BBT Manhattan Portal inbound - West St S Battery Place" linkBorough="Manhattan" linkOwner="NYC_DOT_LIC" linkPolyline="mlmwFr~vbMUKw@AcBj@i@`Aa@vC??l@P??dBf@~BXfEdAp@B" linkPolylineLvl="BBBBBBBBBBBBB" linkSpeed="27.96" linkTravelTime="100" linkStatus="0" linkTimeStamp="12/8/2015 15:24:35" />
<TrafficSpeedData linkId="4456501" linkName="BBT W Toll Plaza - Manhattan Portal" linkBorough="Manhattan" linkOwner="MTA Bridges &amp; Tunnels" linkPolyline="gkhwFp~tbMoJdGkHnCaK`Fat@d`@oe@`NyD|@{L@wHsA{EeB" linkPolylineLvl="BBBBBBBBBB" linkSpeed="14.29" linkTravelTime="446" linkStatus="0" linkTimeStamp="11/14/2016 17:12:40" />
<TrafficSpeedData linkId="4616246" linkName="BE N STRATFORD AVENUE - CASTLE HILL AVE" linkBorough="Bronx" linkOwner="NYC_DOT_LIC" linkPolyline="mmdxFjq{aM}Bm\aBwUa@sIeB_\qCq`@sB{Y" linkPolylineLvl="BBBBBBB" linkSpeed="24.85" linkTravelTime="146" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616260" linkName="BE S CASTLE HILL AVENUE - STRATFORD AVENUE" linkBorough="Bronx" linkOwner="NYC_DOT_LIC" linkPolyline="gndxFvq{aM{Ced@sAqReBa^{Cyb@{Bw[" linkPolylineLvl="BBBBBB" linkSpeed="16.78" linkTravelTime="356" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4456479" linkName="BE S TBB EXIT RAMP - MANHATTAN LIFT SPAN" linkBorough="Queens" linkOwner="MTA Bridges &amp; Tunnels" linkPolyline="yi_xFfndbMb@^Xb@ThAEbB_@nByAbEm@fAkAbDiAlDo@nBaCfIcEfMkBnGeAhD" linkPolylineLvl="BBBBBBBBBBBBBBB" linkSpeed="9.94" linkTravelTime="299" linkStatus="0" linkTimeStamp="11/14/2016 17:12:40" />
<TrafficSpeedData linkId="4456478" linkName="BE S TBB EXIT RAMP - QUEENS ANCHORAGE" linkBorough="Queens" linkOwner="MTA Bridges &amp; Tunnels" linkPolyline="qizwFhndbMkIlMeD`DyIbGyJ`HsOnK{OzKcBf@mBPoCKkBg@uBcAsIiHgGgFuFaEiGoFqMaLmGmFcFsDcHyE{ByA{EcDqGoEeAo@}@e@" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="29.83" linkTravelTime="236" linkStatus="0" linkTimeStamp="11/14/2016 17:12:40" />
<TrafficSpeedData linkId="4616342" linkName="BKN Bridge Manhattan Side - FDR N Catherine Slip" linkBorough="Manhattan" linkOwner="NYC_DOT_LIC" linkPolyline="uxmwFn_tbMgAwBi@eBc@sB[qC[wE" linkPolylineLvl="BBBBBB" linkSpeed="29.2" linkTravelTime="88" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616257" linkName="BQE N ATLANTIC AVENUE - LEONARD STREET" linkBorough="Brooklyn" linkOwner="NYC_DOT_LIC" linkPolyline="aqjwFl}sbMqCr@}B?yAWoCu@{DyAyM_F{KeEcAk@iAgA}@sAcAkBy@kBy@}Ck@kDMmCA{CNyB`@qFbAcMXuB\wAf@qAbA{AbCqCx@aAfGaHhCwChAkAnAkC`@wBP_DpBavAKkDiAkEuAmByBaB_Cg@{LqCuFmBiFeCgNuGqKcFwKmF}EmCcCuAiC}AyCgBaFeD}B{BeKwMyIwN" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="3.11" linkTravelTime="4265" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616339" linkName="BQE N Atlantic Ave - BKN Bridge Manhattan Side" linkBorough="Manhattan" linkOwner="NYC_DOT_LIC" linkPolyline="oqjwFt}sbMwCn@gABoBWkF{AaE}AaBm@mJoDaI}Co@UoAmAyAwBiBiDi@eBg@yB_@mBS{BAuCBeARoCb@{Ej@aA~@_@t@HVXD^C`@u@hBWl@qCtDgChDsH`KyKtNcNjQaCfDiBnCaCrD" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="11.18" linkTravelTime="626" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616340" linkName="BQE N Atlantic Ave - MAN Bridge Manhattan Side" linkBorough="Manhattan" linkOwner="NYC_DOT_LIC" linkPolyline="gplwFnkrbMJ}CZiEh@mGNeBh@{Dh@wBb@cAr@iAl@s@|@u@d@YVGl@A^JTVVn@Dt@Gl@Uf@i@j@eA~@gCjAyDhBcCfA_A`@cB|@wIbEgF~BuPdI}SzI{KbFeGtC{CJ" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="6.21" linkTravelTime="1599" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616235" linkName="BQE N LEONARD STREET - 46TH STREET" linkBorough="Brooklyn" linkOwner="NYC_DOT_LIC" linkPolyline="}sowFx_jbMwDgHuHgOgG}LqBkDmB}CeCeFoD{Hg@qAcAgGuC_Qy@{D}AwD_CqD{BuC{BuCyBcCcEyDqEuCiIuEsBkBiBuBoAqBs@aBeB{FwAgI" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="8.7" linkTravelTime="790" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616229" linkName="BQE S - GOW S ALTANTIC AVENUE - 9TH STREET" linkBorough="Brooklyn" linkOwner="NYC_DOT_LIC" linkPolyline="kngwFzjtbM{CjBiIzG}Ap@yBXeACuA[uBw@uDuAqVoJgK{DkK_E_Ba@yBEuBj@eCt@" linkPolylineLvl="BBBBBBBBBBBBBBBB" linkSpeed="22.99" linkTravelTime="172" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616232" linkName="BQE S 46TH STREET - LEONARD STREET" linkBorough="Brooklyn" linkOwner="NYC_DOT_LIC" linkPolyline="wtowF|_jbMsDcHsHyNgGeM_CyDoB{C_CiF}C}Gs@iBeAcGsCeQw@oDkAuCuCyEwBoCqBkCeCoCaEqD_EgCuIkFsBeBgBsByAaCu@eBiB}FqAiI" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="6.84" linkTravelTime="964" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616271" linkName="BQE S LEONARD STREET - ATLANTIC AVENUE" linkBorough="Brooklyn" linkOwner="NYC_DOT_LIC" linkPolyline="kqjwFp~sbM}Bn@aCAaB_@wCy@aE_BqM}EsLoEo@a@mAiA}@uAeAqBw@mB{@_Di@sDKkC?uCLeC^sF`A{LZ}B\{An@{A`A{AdCmCx@_AfGaHnCuC|@eAlAsC\oBN{CnBsuAQmDc@yBiAeCkBeBoDeAeMqCaGyBsEyByN_HcKyE}KqFgFaCkDq@uCoAaC_B{DmEeCyCaKyMyIkO" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="6.21" linkTravelTime="2542" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616252" linkName="BRP N WATSON AVENUE - FORDHAM ROAD" linkBorough="Bronx" linkOwner="NYC_DOT_LIC" linkPolyline="ewjxF`e{aM~X_EfLs@pRFbE^fUlClPlC`TdE`Gb@|HMtG]fLmBzQaB" linkPolylineLvl="BBBBBBBBBBBBB" linkSpeed="9.94" linkTravelTime="549" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616266" linkName="BRP S FORDHAM ROAD - WATSON AVENUE" linkBorough="Bronx" linkOwner="NYC_DOT_LIC" linkPolyline="wvjxFjf{aMrX_EpKYnJFnNDrTrCdP`CzSdElGb@vHAzG]hLuB|Q{A" linkPolylineLvl="BBBBBBBBBBBBB" linkSpeed="19.26" linkTravelTime="280" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4456497" linkName="BWB N Queens Anchorage - Toll Plaza" linkBorough="Queens" linkOwner="NYC_DOT_LIC" linkPolyline="wr_xFppraM_GjDsXtNci@pYsB~@}Ab@gAHiKD" linkPolylineLvl="BBBBBBBB" linkSpeed="31.69" linkTravelTime="145" linkStatus="0" linkTimeStamp="11/14/2016 17:12:40" />
<TrafficSpeedData linkId="4616305" linkName="BWB N Toll Plaza - HRP N Lafayatte Ave" linkBorough="Bronx" linkOwner="NYC_DOT_LIC" linkPolyline="isbxFxctaMkGCyIs@_NWgVb@iF`@" linkPolylineLvl="BBBBBB" linkSpeed="50.95" linkTravelTime="43" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616312" linkName="BWB S Queens Anchorage - WSE S Exit 14 (Linden Pl)" linkBorough="Queens" linkOwner="NYC_DOT_LIC" linkPolyline="kr_xFpqraM|IgFfJaGbNaIjCqAtDw@vDOlLf@xHfBpOnBzJ`A|Cn@pEfBz[|O|HzEtBdBnElFhElHbAxB" linkPolylineLvl="BBBBBBBBBBBBBBBBBBB" linkSpeed="39.77" linkTravelTime="182" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4456496" linkName="BWB S Toll Plaza - Queens Anchorage" linkBorough="Bronx" linkOwner="NYC_DOT_LIC" linkPolyline="gsbxFfftaMrFQ`BQvBWxBs@rCcBpe@wVnb@iU" linkPolylineLvl="BBBBBBBB" linkSpeed="39.77" linkTravelTime="117" linkStatus="0" linkTimeStamp="11/14/2016 17:12:40" />
<TrafficSpeedData linkId="4616355" linkName="Belt Pkwy E 182nd St - Laurelton Pkwy N @ SSP" linkBorough="Queens" linkOwner="NYC_DOT_LIC" linkPolyline="}sewFnveaMvB{`@HwCDcj@x@oj@SmCWoAw@aCc@eAgBiC_BaB}E}D_XyOiHeFeIwGgTeS_TwMsFsCWE" linkPolylineLvl="BBBBBBBBBBBBBBBBBBB" linkSpeed="18.02" linkTravelTime="492" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616356" linkName="Belt Pkwy W 182nd St - JFK Expressway" linkBorough="Queens" linkOwner="NYC_DOT_LIC" linkPolyline="wtewFjveaMkDlo@YvJAxCD`Pt@ha@`Bt`@" linkPolylineLvl="BBBBBBB" linkSpeed="44.74" linkTravelTime="83" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616357" linkName="Belt Pkwy W JFK Expressway - VWE N Jamaica Ave" linkBorough="Queens" linkOwner="NYC_DOT_LIC" linkPolyline="avewFpljaM|@hR???fDOlFu@dI??D|P??BhSQ~@_@h@??uDdDcAf@}ANiEQkIG??{GXeC^gBj@EH??qQlGiSvHuC|@u]bNwd@jTwQfI{K`GkPxHqPlG" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="6.84" linkTravelTime="1699" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616310" linkName="CBE AMSTERDAM AVE (L/LVL) - MORRIS AVE" linkBorough="Bronx" linkOwner="NYC_DOT_LIC" linkPolyline="gxhxFp{fbMpAiE`@kGhEm[L{FQqIUeKm@}^?gTB{FLgG" linkPolylineLvl="BBBBBBBBBBB" linkSpeed="1.24" linkTravelTime="2844" linkStatus="0" linkTimeStamp="11/2/2016 11:38:30" />
<TrafficSpeedData linkId="4616309" linkName="CBE E AMSTERDAM AVE(U/LVL) - MORRIS AVE" linkBorough="Bronx" linkOwner="NYC_DOT_LIC" linkPolyline="eyhxFxzfbMjBiJpCiQjAoKL_GMiIUqKk@}^CgTBcFN_H" linkPolylineLvl="BBBBBBBBBBB" linkSpeed="34.18" linkTravelTime="121" linkStatus="0" linkTimeStamp="11/2/2016 11:10:30" />
<TrafficSpeedData linkId="4616297" linkName="CBE E CASTLE HILL AVE - BE N WATERBURY AVE" linkBorough="Bronx" linkOwner="NYC_DOT_LIC" linkPolyline="{sexFn}vaMhC_MtAuDrC}Hj@cCTwBFqCIyD]sFwAwSo@uI_AyFe@wBmAmE}A}DwAsCyFqK{DmH}AuD{D_KeCiCiCmAuDQwC`@kH`B" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="29.2" linkTravelTime="232" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616253" linkName="CBE E TAYLOR AVENUE - CASTLE HILL AVENUE" linkBorough="Bronx" linkOwner="NYC_DOT_LIC" linkPolyline="_pfxF`}yaMdFsWfDmPpH}^lEgTBBBBB" linkPolylineLvl="BBBBB" linkSpeed="29.2" linkTravelTime="77" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616267" linkName="CBE W CASTLE HILL AVENUE - TAYLOR AVENUE" linkBorough="Bronx" linkOwner="NYC_DOT_LIC" linkPolyline="cuexFp~vaMcFbWcDtOsC|Nm@pBa@dCk@nDqAfGiAxFgBxI" linkPolylineLvl="BBBBBBBBBB" linkSpeed="3.11" linkTravelTime="345" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4620315" linkName="CBE W L/LE V AMSTERDAM AVE - I 95 S LOC LNS" linkBorough="Bronx" linkOwner="PA-GWBridge" linkPolyline="uzhxFfyfbMcCbIsGfT_CrQu@tJcB|PeF|b@yAjNkAnMiDrZcAnEm@`DSbByAbG" linkPolylineLvl="BBBBBBBBBBBBBB" linkSpeed="11.81" linkTravelTime="661" linkStatus="0" linkTimeStamp="11/2/2016 10:35:58" />
<TrafficSpeedData linkId="4620332" linkName="CBE W MORRIS AVE - GWB W AMSTERDAM AVE (L/LVL)" linkBorough="Bronx" linkOwner="PA-GWBridge" linkPolyline="}zhxFryfbMfC_J~BqOlAgIZkFC_Hq@sZ[wb@ToV" linkPolylineLvl="BBBBBBBBB" linkSpeed="11.18" linkTravelTime="417" linkStatus="0" linkTimeStamp="11/2/2016 10:32:58" />
<TrafficSpeedData linkId="4620331" linkName="CBE W MORRIS AVE - GWB W AMSTERDAM AVE (U/LVL)" linkBorough="Bronx" linkOwner="PA-GWBridge" linkPolyline="{yhxFbzfbMtA}FfDyT|@iGZ_F?_Fe@oSk@i]AkUFgF" linkPolylineLvl="BBBBBBBBBB" linkSpeed="8.08" linkTravelTime="584" linkStatus="0" linkTimeStamp="11/2/2016 10:32:58" />
<TrafficSpeedData linkId="4620310" linkName="CBE W U/LEV AMSTERDAM AVE - I95 S EXP LNS" linkBorough="Bronx" linkOwner="PA-GWBridge" linkPolyline="yyhxFdzfbM_CvH{G`T{BjQcAxJaBrP_F~b@yAnNsAvMoDnZaApEk@bDUrBm@pF" linkPolylineLvl="BBBBBBBBBBBBBB" linkSpeed="27.96" linkTravelTime="290" linkStatus="0" linkTimeStamp="11/2/2016 10:35:58" />
<TrafficSpeedData linkId="4616351" linkName="CIP N Hempstead Tpk - LIE" linkBorough="Queens" linkOwner="NYC_DOT_LIC" linkPolyline="}nnwFla_aM{GhBiBRwFNuDe@aEsAyB{AmJ_IsDqBaCy@yIsBwCe@mt@sJyHu@kCIwDP{CZwB`@gJrCaDnBgGfG}ClFsD~HyGnQeHlNmC~DyDxE{HvIwBxCmCvEqDjHmBtCyCdDsC`CgRpNyIrHwD~DcB`C" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="47.85" linkTravelTime="228" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616320" linkName="CIP N TNB - Whitestone Expwy S Exit 14 (Linden Pl)" linkBorough="Queens" linkOwner="NYC_DOT_LIC" linkPolyline="_u}wFhkjaMr@dI~A~HtA|EbEnKxBdHv@~Cv@jGRhCJ~G[pTm@lT}@nS[vB@p@]dHiAlPo@tEiA|Fu@nCoDvKiAhFa@`DSxCAbAFfAb@lB`AbBjBjA??xHfBpOnBzJ`A|Cn@pEfBz[|O|HzEtBdBrEjFjEjHhAzB" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="42.25" linkTravelTime="198" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4362247" linkName="CIP NB GCP - TNB" linkBorough="Queens" linkOwner="NYC-DOT-Region 10" linkPolyline="em}wFvekaMwByHaAwFy@kKMyFLaK`@uGv@wFrA{FxAiElBiEbBoCvBmCjE{DxFwEzGyFlM{MvE}CbJkDrKqEtIoFlG_GtLiOrCgD~DoB|H}C`IaBpGmBbG{DrDiEzBsD`B{EvAkGlCgL|A}EpCiFlE{ExFoFpD_D|JkHlEoDvEeEhDiE|BoDvDsH`DoF|CwDvEeFzCwEvA_Hw@aI}CiEiEwD{BgBeKiCqDwAwD{CcCyCuCsF_DeG}CoD" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="11.81" linkTravelTime="1294" linkStatus="0" linkTimeStamp="8/5/2016 13:16:46" />
<TrafficSpeedData linkId="4616352" linkName="CIP S Hempstead Tpk - Laurelton Pkwy @ SSP" linkBorough="Queens" linkOwner="NYC_DOT_LIC" linkPolyline="c_owFzf_aMvBK|FcApKuDzF_ArdAkB~j@}@hD?xCInK_AzKM??xCLhDr@" linkPolylineLvl="BBBBBBBBBBBBBB" linkSpeed="31.07" linkTravelTime="245" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616350" linkName="CIP S LIE - Hempstead Tpk" linkBorough="Queens" linkOwner="NYC_DOT_LIC" linkPolyline="yvuwFlcaaMzC}EbD}DvDwDzC{D`DmEbCcEv@eBvJcXvF}KfEcGlCaC`DaBzHyBj@YbE{@bDO|D?vCP|QtBnl@bIzIrB~D~AtCjBrHtGrAz@pCrAbCp@vAR~DF" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="9.94" linkTravelTime="1070" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4362250" linkName="CVE NB GCP - WILLETS PT BLVD" linkBorough="Queens" linkOwner="NYC-DOT-Region 10" linkPolyline="uk}wFtckaMfH}Kr@cAbAoAzAyAvCeCt@e@|EwBxBg@jR_CzTo@pMYfEi@jCk@de@}RbReIrLyEve@sJxMmDb[iL|CwApFkCfAuAPaDcBkKc@uD" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="19.26" linkTravelTime="666" linkStatus="0" linkTimeStamp="11/14/2016 17:13:16" />
<TrafficSpeedData linkId="4362244" linkName="CVE NB LIE - WILLETS PT BLVD" linkBorough="Queens" linkOwner="NYC-DOT-Region 10" linkPolyline="cl}wFtbkaMfFiIdByBrD{DtAeAj@_@nA}@|BcAvBy@hBc@zDm@jBOrBY|C_@f@EpHk@|Is@????bIOrGa@xHcBvFyBtImDzHgDtBcAtCoApCgAbEqA~QuHxGqDbCUbCRjEcApEy@jGeAtEi@dBg@t@SdRyGzHwC|IcDbKuDdLeEnM}ExOwFzRsHnCoArGeEtOaQjGqMbCoJ|@{GDuIe@Sf" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="36.04" linkTravelTime="218" linkStatus="0" linkTimeStamp="11/14/2016 17:13:16" />
<TrafficSpeedData linkId="4456450" linkName="FDR N - TBB E 116TH STREET - MANHATTAN TRUSS" linkBorough="Manhattan" linkOwner="MTA Bridges &amp; Tunnels" linkPolyline="i{_xFzefbMyBvGUlACt@Rj@d@f@z@@`@W\g@bA_DTk@b@i@`@a@n@YhAKjGYp@M`DTtCf@|@\xBrA~@z@dBnD" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="29.83" linkTravelTime="78" linkStatus="0" linkTimeStamp="11/14/2016 12:19:54" />
<TrafficSpeedData linkId="4616329" linkName="FDR N 25th - 63rd St" linkBorough="Manhattan" linkOwner="NYC_DOT_LIC" linkPolyline="slswFpdobMcJ{Fy@_@sBq@kKeBaDc@eB_@iBs@kC{AuBkAqDqC_EiEyCuCcDaCeT}PuJuIrAhAcE{CaEkDcEkFsEiD}FiEiHoFcAwA}BoD" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="21.75" linkTravelTime="313" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616328" linkName="FDR N Catherine Slip - 25th St" linkBorough="Manhattan" linkOwner="NYC_DOT_LIC" linkPolyline="w~mwFjisbMc@}HkCe^gBoZe@iQe@mJSaBYmA_A{BuBqCcCsAaFsBcGgCeGaCgDiAeEs@mJs@oHc@yCg@yDiB_J{EiFeCyDq@yE]gB?eALiA\eAz@yBdCuBbCcAl@}D`AeDl@kNvBaAF}AMeBc@" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="31.07" linkTravelTime="331" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616333" linkName="FDR S 25th St - Catherine Slip" linkBorough="Manhattan" linkOwner="NYC_DOT_LIC" linkPolyline="amswFheobMzAn@nBHdD]rE{@hGaAjEq@bAc@pAs@x@}@~AyBhBaBfB{@vBU~ADpBNnCXnB`@zCpAtEdCjE`CxBhAvAl@hC\pCPbDPlDPpDZ|B\|Cz@fA\XVbGzBpElBfIfDpAz@dBvBl@lAf@dC`@`EVtKXnIj@dKt@vN|@tL|AvSh@lH" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="13.05" linkTravelTime="787" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616332" linkName="FDR S 63rd - 25th St" linkBorough="Manhattan" linkOwner="NYC_DOT_LIC" linkPolyline="iaxwF|tkbMhBnCtChChGpEjGxE~CvBxEnGlGhFrA|AfAp@hEdEbGtEpF~DzE|DvGhFlGhG~CxB|EjC~BfA`Dv@zMfBxAd@bChApBrA~DfC" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="39.77" linkTravelTime="171" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616341" linkName="FDR S Catherine Slip - BKN Bridge Manhattan Side" linkBorough="Manhattan" linkOwner="NYC_DOT_LIC" linkPolyline="w~mwFjisbMXnEXdCh@bCf@zAd@jA^r@" linkPolylineLvl="BBBBBBB" linkSpeed="3.73" linkTravelTime="557" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616334" linkName="FDR S Catherine Slip - Whitehall St" linkBorough="Manhattan" linkOwner="NYC_DOT_LIC" linkPolyline="e_nwFnisbMf@fHn@zCr@lCzA|ChBfEdFfLzE|I`GlKfFxJpAbCl@zAb@hBdAhHd@zD" linkPolylineLvl="BBBBBBBBBBBBBBB" linkSpeed="8.7" linkTravelTime="156" linkStatus="0" linkTimeStamp="12/8/2015 15:24:35" />
<TrafficSpeedData linkId="4456495" linkName="FDR S Whitehall St - BBT Manhattan Portal outbound" linkBorough="Manhattan" linkOwner="NYC_DOT_LIC" linkPolyline="cnlwFhuvbMc@xE_@jB}AfCiCbBgCbAaDf@mBJe@?qA[wA_@aBe@y@c@eBi@" linkPolylineLvl="BBBBBBBBBBBBBB" linkSpeed="31.69" linkTravelTime="111" linkStatus="0" linkTimeStamp="7/15/2015 10:56:05" />
<TrafficSpeedData linkId="4616318" linkName="GOW N 7TH AVENUE - 9TH STREET" linkBorough="Brooklyn" linkOwner="NYC_DOT_LIC" linkPolyline="ue_wFbfwbMyBJyAX_Bp@oBhBiD|FmGxL_BzBuAbAoBv@mBNiBMiCaAuCcCuD_EmMiM{V{Wq~@_aAmb@wc@qB_BkDsA{BQkDN}FrBqX|NsFvC_FnCuAn@" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="8.08" linkTravelTime="1499" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616220" linkName="GOW N 92ND STREET - 7TH AVENUE" linkBorough="Brooklyn" linkOwner="NYC_DOT_LIC" linkPolyline="oz{vFffybMuQuNmZsVsFyC}D}AeLmDeO_E{JkCaEg@" linkPolylineLvl="BBBBBBBBB" linkSpeed="52.2" linkTravelTime="83" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616223" linkName="GOW N 9TH STREET - ATLANTIC AVENUE" linkBorough="Brooklyn" linkOwner="NYC_DOT_LIC" linkPolyline="omgwFfhtbMeDnAaDbB_F|CqDzC_ARwAQqBy@qDuAmVoJkK}DsK_EcBc@yBAuBb@yBt@" linkPolylineLvl="BBBBBBBBBBBBBBBB" linkSpeed="3.73" linkTravelTime="875" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616226" linkName="GOW S 7TH AVENUE - 92ND STREET" linkBorough="Brooklyn" linkOwner="NYC_DOT_LIC" linkPolyline="_{{vFjgybMoQ}NwZwVwEkCmEeBgLiD{OuDwIcCkDa@" linkPolylineLvl="BBBBBBBBB" linkSpeed="42.25" linkTravelTime="101" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616319" linkName="GOW S 9TH STREET - 7TH AVENUE" linkBorough="Brooklyn" linkOwner="NYC_DOT_LIC" linkPolyline="ud_wF|gwbMgCCwATcBr@_BvAqDhGmGtL{AxB}AlAsBt@uBViCYeCy@wBqAkCeCeOcP_WgXm~@aaAmb@yc@cBuAwCqAmCUoDPuFdBsX`OwFlCaFzC{BvA" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="42.87" linkTravelTime="291" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4763657" linkName="GOW S VNB W 92ND STREET - BKLYN GANTRY LOWER LEVEL" linkBorough="Brooklyn" linkOwner="Verrazano-Narrows-Bridge" linkPolyline="{izvFxx{bMoMkl@_AiB_BaBqFkEwDgEkCeDcKiJ" linkPolylineLvl="BBBBBBBB" linkSpeed="44.12" linkTravelTime="56" linkStatus="0" linkTimeStamp="11/14/2016 17:12:40" />
<TrafficSpeedData linkId="4763655" linkName="GOW S VNB W 92ND STREET - BKLYN GANTRY UPPER LEVEL" linkBorough="Brooklyn" linkOwner="Verrazano-Narrows-Bridge" linkPolyline="kizvFrx{bMqMol@cAsByAcBsFkEoCgE}CqD_LeJ" linkPolylineLvl="BBBBBBBB" linkSpeed="37.9" linkTravelTime="60" linkStatus="0" linkTimeStamp="11/14/2016 17:12:40" />
<TrafficSpeedData linkId="4620298" linkName="GWB E LOWER LEVEL PLAZA - CBE E LOWER LEVEL AMSTERDAM AVE" linkBorough="Manhattan" linkOwner="PA-GWBridge" linkPolyline="axhxF~zfbMkCfHeHfTyBbQeAtJgBvPgExb@aBhN}AbNuD~Yq@|Da@`DQpCY|F" linkPolylineLvl="BBBBBBBBBBBBBB" linkSpeed="55.3" linkTravelTime="135" linkStatus="0" linkTimeStamp="11/2/2016 10:35:58" />
<TrafficSpeedData linkId="4616250" linkName="HRP N LAFAYETTE AVENUE - E TREMONT AVENUE" linkBorough="Bronx" linkOwner="NYC_DOT_LIC" linkPolyline="_ugxFlptaMlJj@bY[rKeAdKgBdOgDnR}A" linkPolylineLvl="BBBBBBB" linkSpeed="50.95" linkTravelTime="64" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4456498" linkName="HRP S Lafayette Ave - BWB S Toll Plaza" linkBorough="Bronx" linkOwner="NYC_DOT_LIC" linkPolyline="_tdxFhdtaMjCOxHMvGAxN\zU`A|AA" linkPolylineLvl="BBBBBBB" linkSpeed="47.85" linkTravelTime="53" linkStatus="0" linkTimeStamp="11/9/2016 08:59:48" />
<TrafficSpeedData linkId="4362342" linkName="LIE E 84TH ST - 108TH ST" linkBorough="Queens" linkOwner="NYC_DOT_LIC" linkPolyline="k_rwF|f|aMcBgGo@wCqK{g@uJ_d@wCuOuBuJ}D_TgAwKcA}G" linkPolylineLvl="BBBBBBBBBB" linkSpeed="3.73" linkTravelTime="80" linkStatus="0" linkTimeStamp="11/14/2016 17:13:17" />
<TrafficSpeedData linkId="4616365" linkName="LIE E QMT TOLL PLAZA - 84TH ST" linkBorough="Queens" linkOwner="NYC_DOT_LIC" linkPolyline="shtwFxckbMTmJ_AiK?}BvAwNlBsNrCqJ`GoQjAcFl@mE~@oM~Eqe@xBgSl@eD|@mDbBiEbByCjIoLjB_DbAgC`AsDbAgFnBqKdCwO~@kEbBwErHiN~AmDz@_CdAsDbAqGz@sOxAe\ZwJCwF]eEc@qCaAyDkB{EiEkIk@_BgAoE}@kIw@gS]_Em@kD{ByI" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="54.06" linkTravelTime="271" linkStatus="0" linkTimeStamp="11/3/2016 02:58:32" />
<TrafficSpeedData linkId="4616364" linkName="LIE W 108TH ST - 84TH ST" linkBorough="Queens" linkOwner="NYC_DOT_LIC" linkPolyline="_pswFfewaMtApJv@rIh@nDlFbXhH`]bJla@|@`FbHz\fBvG" linkPolylineLvl="BBBBBBBBBB" linkSpeed="16.16" linkTravelTime="282" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4456516" linkName="LIE W 84TH ST - QMT TOLL PLAZA" linkBorough="Queens" linkOwner="NYC_DOT_LIC" linkPolyline="c`rwF~g|aMbClIr@vDd@rIXjJZfFp@rFbA`Ed@rAdE`ItBnFtA|Ff@~EJhCAnDoCrq@YjEcA`GsA`FcB~DsIdPmBnFmAfGsAfJoFfYkB~EeMlQoA~BgAfCu@|BaA`EuEh_@{AtQcAtIaAnN[dCgAfFqJfZcAdE}ArMoA~KIrABjDT~EHzM" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="19.26" linkTravelTime="688" linkStatus="0" linkTimeStamp="11/14/2016 17:12:40" />
<TrafficSpeedData linkId="4362249" linkName="LIE WB LITTLE NECK PKWY - NB CIP" linkBorough="Queens" linkOwner="NYC-DOT-Region 10" linkPolyline="kztwFzogaMqFeOu@wC_DeQcFwXyAoF{CkIaAmDu@aEiDeTiAeL]iDg@mEqA{E_B_EeCgEgGsKiLmScIkNoH}N}AeEaAaEqC_KqAuDaCsE_EgHqByEaBiGw@kDi@wE" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="16.16" linkTravelTime="237" linkStatus="0" linkTimeStamp="11/14/2016 17:13:16" />
<TrafficSpeedData linkId="4362251" linkName="LIE WB LITTLE NECK PKWY - NB CVE" linkBorough="Queens" linkOwner="NYC-DOT-Region 10" linkPolyline="}uvwFlebaMkMcUcIkNoH}N}AeEaAaEqC_KqAuDaCsE_EgHqByEaBiGw@kDi@wE" linkPolylineLvl="BBBBBBBBBBBBBB" linkSpeed="36.04" linkTravelTime="354" linkStatus="0" linkTimeStamp="11/14/2016 17:13:16" />
<TrafficSpeedData linkId="4329473" linkName="LINCOLN TUNNEL E CENTER TUBE NJ - NY" linkBorough="Manhattan" linkOwner="PA -Lincoln Tunnel" linkPolyline="iowwF~nsbMoObg@yH|VeY|}@" linkPolylineLvl="BBBB" linkSpeed="11.18" linkTravelTime="489" linkStatus="0" linkTimeStamp="11/2/2016 10:35:58" />
<TrafficSpeedData linkId="4329472" linkName="LINCOLN TUNNEL E SOUTH TUBE - NJ - NY" linkBorough="Manhattan" linkOwner="PA -Lincoln Tunnel" linkPolyline="irwwFpssbMyLlb@wHzVmYv}@" linkPolylineLvl="BBBB" linkSpeed="8.08" linkTravelTime="634" linkStatus="0" linkTimeStamp="11/2/2016 10:35:58" />
<TrafficSpeedData linkId="4329508" linkName="LINCOLN TUNNEL W CENTER TUBE NY - NJ" linkBorough="Manhattan" linkOwner="PA -Lincoln Tunnel" linkPolyline="knwwFlosbMcP`g@yHzVcY|}@" linkPolylineLvl="BBBB" linkSpeed="44.12" linkTravelTime="126" linkStatus="0" linkTimeStamp="11/1/2016 23:11:56" />
<TrafficSpeedData linkId="4329507" linkName="LINCOLN TUNNEL W NORTH TUBE NY - NJ" linkBorough="Manhattan" linkOwner="PA -Lincoln Tunnel" linkPolyline="mkwwFvqsbMsQbh@oIlTmYp}@" linkPolylineLvl="BBBB" linkSpeed="18.02" linkTravelTime="248" linkStatus="0" linkTimeStamp="11/2/2016 10:35:58" />
<TrafficSpeedData linkId="4616353" linkName="Laurelton Pkwy N @ SSP - CIP N Hempstead Tpk" linkBorough="Queens" linkOwner="NYC_DOT_LIC" linkPolyline="u}hwFlv~`M{@a@oB{A_BiBkAgB??g@m@cBw@oAUcBLo@VmA`AoEtEcBfAoBj@U???wI\gD?_b@z@m`AjAyERaC\{DfAoDxA" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="49.71" linkTravelTime="157" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616354" linkName="Laurelton Pkwy S @ SSP - Belt Pkwy W 182nd St" linkBorough="Queens" linkOwner="NYC_DOT_LIC" linkPolyline="w_iwFtv~`MbBp@bJbFbN`JlC~BhJtJfFrEdHvFtDhCnW~OtAp@nE~CfB`BjBvBlCxGXlALrB}@xXCby@KpDyBva@" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBB" linkSpeed="52.2" linkTravelTime="177" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4575278" linkName="MDE N VAN CORTLAND PARK - NYST N EXIT 1 (MP.48)" linkBorough="Bronx" linkOwner="NYC Thruway Tarrytown" linkPolyline="cppxF`|_bMmDuFkBaEkCiIkAcGcBmKkAmEwAeDwAeCkB_CmB_CsDmDkZgY{EcCuDwA}GmAmEWs`@uDgP}AsEyA_CaBuBsBuCkD" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="37.9" linkTravelTime="234" linkStatus="0" linkTimeStamp="3/21/2014 15:23:00" />
<TrafficSpeedData linkId="4620330" linkName="MDE S HARLEM RIVER PARK - GWB W AMSTERDAM AVENUE LOWER LEVEL" linkBorough="Bronx" linkOwner="NYC_DOT_LIC" linkPolyline="qojxFpfdbMrN|LlO`NtTtQ~FtClClAv@Ar@k@XkAQsBsAqDgB}@aBx@k@bCZnC" linkPolylineLvl="BBBBBBBBBBBBBBB" linkSpeed="11.81" linkTravelTime="371" linkStatus="0" linkTimeStamp="11/2/2016 10:32:58" />
<TrafficSpeedData linkId="4620314" linkName="MDE S HARLEM RIVER PARK - GWB W AMSTERDAM AVENUE UPPER LEVEL" linkBorough="Bronx" linkOwner="NYC_DOT_LIC" linkPolyline="kpjxFdfdbMfObMjObNtOjL`G`ErCzAlAVv@UXa@`@w@NeAKiA_@s@o@]UC" linkPolylineLvl="BBBBBBBBBBBBBBB" linkSpeed="9.94" linkTravelTime="428" linkStatus="0" linkTimeStamp="11/2/2016 10:35:58" />
<TrafficSpeedData linkId="4456477" linkName="MDE S TBB EXIT RAMP - QUEENS ANCHORAGE" linkBorough="Queens" linkOwner="MTA Bridges &amp; Tunnels" linkPolyline="mizwFrndbM_HvKuC~C_PhLqWpQwKrHwBxAeBh@mBPoCKmBg@yBkAeRwOgFqDqGwFmDgDwE{DiJyHqDkCsGmE{DsCwCmByGoE}AcAmAo@" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="31.07" linkTravelTime="230" linkStatus="0" linkTimeStamp="11/14/2016 17:12:40" />
<TrafficSpeedData linkId="4329499" linkName="MLK N WALKER STREET - NJ ROUTE 169" linkBorough="Staten Island" linkOwner="NYC_DOT_LIC" linkPolyline="cv~vFpqpcMqI_@_JoA{Dk@mY}Ig^yKwL{DyCmA{]_UgDyC_BqCs@oCUuBGkCDqDf@wYSgI]sDsAgIaByGcFuM" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBB" linkSpeed="22.99" linkTravelTime="161" linkStatus="0" linkTimeStamp="10/11/2016 14:59:04" />
<TrafficSpeedData linkId="4616196" linkName="MLK S - SIE E WALKER STREET - WOOLEY AVENUE" linkBorough="Staten Island" linkOwner="NYC_DOT_LIC" linkPolyline="gv~vF~rpcMhF@bE[bDWbD@vCb@|D~@dCf@`Cv@jCjA~CzAhDfCrDjDfJ~IhDhDxB~AlDlBdEdArDp@jC|BjGvEtBjArCC|BmAtA_Cj@gDXgI^mCnBkD`AiC" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="1.86" linkTravelTime="7693" linkStatus="0" linkTimeStamp="11/7/2016 11:25:35" />
<TrafficSpeedData linkId="4616210" linkName="MLK S - SIE W WALKER STREET - RICHMOND AVENUE" linkBorough="Staten Island" linkOwner="NYC_DOT_LIC" linkPolyline="gv~vF~rpcMhF@bE[bDWbD@vCb@|D~@dCf@`Cv@jCjA~CzAhDfCrDjDfJ~IhDhDxB~AlDlBdEdArDp@jC|Bt@zBCjDeB~DgAzA" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="1.86" linkTravelTime="1142" linkStatus="0" linkTimeStamp="11/7/2016 11:50:35" />
<TrafficSpeedData linkId="4456511" linkName="QMT E Manhattan Side - Toll Plaza" linkBorough="Manhattan" linkOwner="NYC_DOT_LIC" linkPolyline="wcuwF|}nbMTkB?qAwAuRd@qEbBqKnMk]vB{Ir@_EtCwWLaF" linkPolylineLvl="BBBBBBBBBBB" linkSpeed="9.94" linkTravelTime="387" linkStatus="0" linkTimeStamp="11/14/2016 17:12:40" />
<TrafficSpeedData linkId="4456510" linkName="QMT W Toll Plaza - Manhattan Side" linkBorough="Queens" linkOwner="NYC_DOT_LIC" linkPolyline="qitwFzckbMDhDkEh]wB~ImM|\_DtRnApR]nDoCnI" linkPolylineLvl="BBBBBBBBB" linkSpeed="8.08" linkTravelTime="492" linkStatus="0" linkTimeStamp="11/14/2016 17:12:40" />
<TrafficSpeedData linkId="4616282" linkName="ROUTE 169 S - MLK WALKER STREET" linkBorough="Staten Island" linkOwner="NYC_DOT_LIC" linkPolyline="_ucwFfokcM~FxO|BdKx@nHTzFw@vc@F~Dh@|BzAhDv@|@~`@dW`DtAbObFv]rKpUhHfFvAtMtBfH`@" linkPolylineLvl="BBBBBBBBBBBBBBBBBB" linkSpeed="1.86" linkTravelTime="1299" linkStatus="0" linkTimeStamp="11/7/2016 11:25:35" />
<TrafficSpeedData linkId="4616193" linkName="SIE E BRADLEY AVENUE - CLOVE ROAD" linkBorough="Staten Island" linkOwner="NYC_DOT_LIC" linkPolyline="wvzvFpegcMrAfeAc@vHiCtNSrOv@|HxGf_@|Db^lAp\" linkPolylineLvl="BBBBBBBBB" linkSpeed="55.3" linkTravelTime="120" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616192" linkName="SIE E CLOVE ROAD - FINGERBOARD ROAD" linkBorough="Staten Island" linkOwner="NYC_DOT_LIC" linkPolyline="wvzvFnegcMGmJ~@kKpAoGxPki@~AyJbA}Kf@ac@`BeOzHgY" linkPolylineLvl="BBBBBBBBBB" linkSpeed="45.98" linkTravelTime="109" linkStatus="0" linkTimeStamp="9/14/2016 16:58:51" />
<TrafficSpeedData linkId="4616195" linkName="SIE E RICHMOND AVENUE - WOOLEY AVENUE" linkBorough="Staten Island" linkOwner="NYC_DOT_LIC" linkPolyline="{q{vFrzrcMta@kl@hDiInBiIr@}F\mHOsR" linkPolylineLvl="BBBBBBB" linkSpeed="49.09" linkTravelTime="78" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616197" linkName="SIE E SOUTH AVENUE - RICHMOND AVENUE" linkBorough="Staten Island" linkOwner="NYC_DOT_LIC" linkPolyline="ix|vFjbucMp@kD|Ncb@pP_ZzAsB" linkPolylineLvl="BBBBB" linkSpeed="49.09" linkTravelTime="49" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4763650" linkName="SIE E VNB E FINGERBOARD ROAD - SI GANTRY LOWER LEVEL" linkBorough="Staten Island" linkOwner="NYC_DOT_LIC" linkPolyline="onyvFni~bMrAfG|@lEfApEjDlOt@nDV`EBdDM~CKlD_@hFa@`C}Il\" linkPolylineLvl="BBBBBBBBBBBBB" linkSpeed="45.98" linkTravelTime="55" linkStatus="0" linkTimeStamp="11/14/2016 17:12:40" />
<TrafficSpeedData linkId="4763648" linkName="SIE E VNB E FINGERBOARD ROAD - SI GANTRY UPPER LEVEL" linkBorough="Staten Island" linkOwner="NYC_DOT_LIC" linkPolyline="}myvFpi~bMvAjG`AnE`AlExDlPr@~CXxDFlFO`DYtBg@xE_@|BiIr\" linkPolylineLvl="BBBBBBBBBBBBB" linkSpeed="50.95" linkTravelTime="49" linkStatus="0" linkTimeStamp="11/14/2016 17:12:40" />
<TrafficSpeedData linkId="4616194" linkName="SIE E WOOLEY AVENUE - BRADLEY AVENUE" linkBorough="Staten Island" linkOwner="NYC_DOT_LIC" linkPolyline="egzvFt|mcMvA|u@" linkPolylineLvl="BB" linkSpeed="47.22" linkTravelTime="34" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616216" linkName="SIE E-MLK N RICHMOND AVENUE - WALKER STREET" linkBorough="Staten Island" linkOwner="NYC_DOT_LIC" linkPolyline="av~vFpqpcMxE?`EYzCUfD@|CZtDdAnCd@`Cz@rCdAzCzAvDlCzNlNfEfEbChBhD~AjJnBnVzDtA]|@cBD_Bq@qAaBD" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="49.71" linkTravelTime="172" linkStatus="0" linkTimeStamp="11/1/2016 19:12:29" />
<TrafficSpeedData linkId="4616217" linkName="SIE W - MLK N WOOLEY AVENUE - WLAKER STREET" linkBorough="Staten Island" linkOwner="NYC_DOT_LIC" linkPolyline="m}{vFr{qcMdEbAtDh@vC]nEmBtOwGrCyC" linkPolylineLvl="BBBBBBB" linkSpeed="11.81" linkTravelTime="589" linkStatus="0" linkTimeStamp="11/1/2016 22:43:29" />
<TrafficSpeedData linkId="4616199" linkName="SIE W - WSE S SOUTH AVENUE - SOUTH AVENUE" linkBorough="Staten Island" linkOwner="NYC_DOT_LIC" linkPolyline="ibyvFzyxcMeQsQmJwGiQcIid@qU{GmBsKgC{HyHuCsGcA{E_@mH\eCjCoLaCxK" linkPolylineLvl="BBBBBBBBBBBBBB" linkSpeed="57.17" linkTravelTime="116" linkStatus="0" linkTimeStamp="10/31/2016 11:15:35" />
<TrafficSpeedData linkId="4616208" linkName="SIE W BRADLEY AVENUE - WOOLEY AVENUE" linkBorough="Staten Island" linkOwner="NYC_DOT_LIC" linkPolyline="sezvFtsocM_Bav@" linkPolylineLvl="BB" linkSpeed="13.05" linkTravelTime="110" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616206" linkName="SIE W FINGERBOARD ROAD - CLOVE ROAD" linkBorough="Staten Island" linkOwner="NYC_DOT_LIC" linkPolyline="_xzvF|fgcMEgIZcInAkIhBqG|FwQlFyQtA{F|@_JVqIRuXd@aIzAyKrByItDoM" linkPolylineLvl="BBBBBBBBBBBBBBB" linkSpeed="16.78" linkTravelTime="360" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616211" linkName="SIE W RICHMOND AVENUE - SOUTH AVENUE" linkBorough="Staten Island" linkOwner="NYC_DOT_LIC" linkPolyline="ys{vFrzrcM{LzRuRdf@sAvEQv@[lB" linkPolylineLvl="BBBBBB" linkSpeed="21.13" linkTravelTime="101" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4329480" linkName="SIE W SOUTH AVENUE - 278 W BRUNSWICK AVENUE" linkBorough="Staten Island" linkOwner="NYC_DOT_LIC" linkPolyline="iy|vFraucMk@bFo@tKcAnHy@tCsC|F}OrQkC`EkCjFuFfLsGbPgl@ptA" linkPolylineLvl="BBBBBBBBBBBB" linkSpeed="11.18" linkTravelTime="1003" linkStatus="0" linkTimeStamp="12/3/2014 10:03:36" />
<TrafficSpeedData linkId="4616209" linkName="SIE W WOOLEY AVENUE - RICHMOND AVENUE" linkBorough="Staten Island" linkOwner="NYC_DOT_LIC" linkPolyline="at{vFvzrcMbQsVlP{UjCkFbBsFxAkJ\{HKiS" linkPolylineLvl="BBBBBBBB" linkSpeed="21.13" linkTravelTime="141" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616225" linkName="TBB N QUEENS ANCHORAGE - BE N" linkBorough="Queens" linkOwner="NYC_DOT_LIC" linkPolyline="ajzwFtmdbMmHhLyBbCkEhDiQrLsOjKcOjKcCx@_DJmC[{Am@}A_AsFyEsJkIgPkM{BiBuDiDkFiF{DsCuDaCqC_BqEuDeUwOcAkA" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="42.25" linkTravelTime="171" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4456476" linkName="TBB N QUEENS ANCHORAGE - MANHATTAN LIFT SPAN" linkBorough="Queens" linkOwner="MTA Bridges &amp; Tunnels" linkPolyline="{izwF|mdbMqHjLwB~BmEhDgQpLqOnKgOjK_Cv@eDNmCY_Bo@eBiAmFsEyJkIcPmM_D}DcAkAiG}HsBwB{CqDcAg@_AFi@Ve@|@]hBMjBs@zD_AnDgD`KcDhKeEpMs@vAqAlB{AnE" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="11.81" linkTravelTime="662" linkStatus="0" linkTimeStamp="11/14/2016 17:12:40" />
<TrafficSpeedData linkId="4456481" linkName="TBB S MANHATTAN LIFT SPAN - QUEENS ANCHORAGE" linkBorough="Queens" linkOwner="MTA Bridges &amp; Tunnels" linkPolyline="mizwFrndbM_HvKuC~C_PhLqWpQwKrHwBxAeBh@mBPoCKmBg@yBkAeRwOgFqDqGwFuDsCcAaAkOgJaBc@{Bn@w@~@u@hAi@pAiFvMoCnHqD~Kk@xCYtCmA|D" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="1.24" linkTravelTime="5511" linkStatus="0" linkTimeStamp="11/14/2016 13:49:55" />
<TrafficSpeedData linkId="4456452" linkName="TBB W - FDR S MANHATTAN TRUSS - E116TH STREET" linkBorough="Manhattan" linkOwner="MTA Bridges &amp; Tunnels" linkPolyline="{}_xFzcfbMqAvLTxA`@b@t@Vj@On@u@n@aBp@mBp@{@bAi@pAKbGUjCErBTvBf@dB|@rAdAf@v@tAnC" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBB" linkSpeed="21.75" linkTravelTime="108" linkStatus="0" linkTimeStamp="11/14/2016 17:12:40" />
<TrafficSpeedData linkId="4456505" linkName="TNB N Queens Anchorage - Toll Plaza" linkBorough="Queens" linkOwner="NYC_DOT_LIC" linkPolyline="ii_xFnvkaMiZF}`@h@wL?kGf@yEjA{E`CgDbCmBfB{BhCyChFcBfEwBlH_AnG{@bK" linkPolylineLvl="BBBBBBBBBBBBBBB" linkSpeed="49.71" linkTravelTime="144" linkStatus="0" linkTimeStamp="11/14/2016 17:12:40" />
<TrafficSpeedData linkId="4362314" linkName="TNB S Qns Anchorage - CIP S @ TNB" linkBorough="Queens" linkOwner="NYC_DOT_LIC" linkPolyline="ki_xFtwkaMnZH|BM|Ce@bFsA??vCo@bJm@t@a@X]XsAFg@Aq@OgAkFgPw@wI" linkPolylineLvl="BBBBBBBBBBBBBBBB" linkSpeed="22.99" linkTravelTime="278" linkStatus="0" linkTimeStamp="9/2/2016 13:57:17" />
<TrafficSpeedData linkId="4456506" linkName="TNB S Toll Plaza - Queens Anchorage" linkBorough="Queens" linkOwner="NYC_DOT_LIC" linkPolyline="eecxFrwmaMViEx@cJz@eEtBaHbBoD`CwD|CkDjDkC|EkCnBs@rCq@~Eg@fy@m@|P?" linkPolylineLvl="BBBBBBBBBBBBBBB" linkSpeed="37.9" linkTravelTime="180" linkStatus="0" linkTimeStamp="11/13/2016 22:02:51" />
<TrafficSpeedData linkId="4763656" linkName="VNB E SI GANTRY LOWER LEVEL - BROOLKYN GANTRY LOWER LEVEL" linkBorough="Brooklyn" linkOwner="Verrazano-Narrows-Bridge" linkPolyline="ymyvFvi~bMgC}K_Pms@sBqJs@{C" linkPolylineLvl="BBBBB" linkSpeed="42.87" linkTravelTime="77" linkStatus="0" linkTimeStamp="11/14/2016 17:12:40" />
<TrafficSpeedData linkId="4763652" linkName="VNB E SI GANTRY UPPER LEVEL - BROOKLYN GANTRY UPPER LEVEL" linkBorough="Brooklyn" linkOwner="Verrazano-Narrows-Bridge" linkPolyline="gnyvF~i~bMcCsKaPys@wBuJo@yC" linkPolylineLvl="BBBBB" linkSpeed="37.28" linkTravelTime="117" linkStatus="0" linkTimeStamp="11/14/2016 17:12:40" />
<TrafficSpeedData linkId="4616218" linkName="VNB E-GOWANUS N BROOKLYN GANTRY LOWER LEVEL - 92ND STREET" linkBorough="Brooklyn" linkOwner="NYC_DOT_LIC" linkPolyline="ahzvFjx{bM_Kyc@cBaI{BgHcBgC{F_EyDaDkMiJ" linkPolylineLvl="BBBBBBBB" linkSpeed="47.85" linkTravelTime="50" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616219" linkName="VNB E-GOWANUS N BROOKLYN GANTRY UPPER LEVEL - 92ND STREET" linkBorough="Brooklyn" linkOwner="NYC_DOT_LIC" linkPolyline="uhzvFjx{bM}J{c@aB{HkCqHqAqBaG}DaEoCwLsJ" linkPolylineLvl="BBBBBBBB" linkSpeed="45.98" linkTravelTime="50" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4763651" linkName="VNB W BROOKLYN GANTRY LOWER LEVEL - SI GANTRY LOWER LEVEL" linkBorough="Brooklyn" linkOwner="Verrazano-Narrows-Bridge" linkPolyline="qoyvF`j~bM{BgKeP}s@yBsJQu@[wA" linkPolylineLvl="BBBBBB" linkSpeed="44.12" linkTravelTime="97" linkStatus="0" linkTimeStamp="11/14/2016 17:12:40" />
<TrafficSpeedData linkId="4763649" linkName="VNB W BROOKLYN GANTRY UPPER LEVEL - SI GANTRY UPPER LEVEL" linkBorough="Brooklyn" linkOwner="Verrazano-Narrows-Bridge" linkPolyline="{nyvFpj~bMaC{KcP{s@qBwJw@yC" linkPolylineLvl="BBBBB" linkSpeed="31.07" linkTravelTime="129" linkStatus="0" linkTimeStamp="11/14/2016 17:12:40" />
<TrafficSpeedData linkId="4616205" linkName="VNB W-SIE W SI GANTRY LOWER LEVEL - FINGERBOARD ROAD" linkBorough="Staten Island" linkOwner="NYC_DOT_LIC" linkPolyline="qoyvF~i~bMhAhF`ArEdAtEbDtNp@lDRvDKrDc@~Dm@bFy@dGa@tEoFrV" linkPolylineLvl="BBBBBBBBBBBBB" linkSpeed="18.02" linkTravelTime="137" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616204" linkName="VNB W-SIE W SI GANTRY UPPER LEVEL - FINGERBOARD ROAD" linkBorough="Staten island" linkOwner="NYC_DOT_LIC" linkPolyline="coyvFzi~bMrAzF~@lEfAxEfD~Np@nDVfEKfD]rEq@vEaAdGo@xDiFvV" linkPolylineLvl="BBBBBBBBBBBBB" linkSpeed="16.78" linkTravelTime="100" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616298" linkName="VWE N MP4.63 (Exit 6 - Jamaica Ave) - MP6.39 (Exit 11 Jewel Ave)" linkBorough="Queens" linkOwner="NYC_DOT_LIC" linkPolyline="gtqwFvmsaM`DyAnBoA~AeBzF{J`B_C`BgBhBaB~CoBdBaAtAw@nB}@|Ac@pAOx@Ez@AfCNj@Bh@LhDRtAExAQhA[x@Y~AcAxE}DbBeAjAg@t@Ur@c@tJgLlAwAdAy@t@q@jEcDvC_B|EeCp@a@x@_@bMwFtBq@xGcC" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="24.23" linkTravelTime="368" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616299" linkName="VWE N MP6.39 (Exit 11 Jewel Ave) - MP8.65 (Exit 13 Northern Blvd)" linkBorough="Queens" linkOwner="NYC_DOT_LIC" linkPolyline="olxwFdwtaMpBu@jAg@|@Yr@MdAGhA@dH\~@E|@GbMoAbCa@`Be@|Aq@`EaCvMeI|BqAbAa@vA_@dAMhAGjA@jAL|@N|Aj@tBhA~BlBnFnEp@^xAr@vCh@jDJ~AIdAO`GiApFgAvCc@~Qy@rC[nBi@lCeAjKmEpNcGjEkB" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="11.81" linkTravelTime="309" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616300" linkName="VWE N MP8.64 (Exit 13 Northern Blvd) - Whitestone Expwy Exit 14 (Linden Pl)" linkBorough="Queens" linkOwner="NYC_DOT_LIC" linkPolyline="iczwFlqsaMvBtEtBbEnChEvBfBxCdCnCjAjGtD`AZpBbAjAb@dARdBLnACz@MtBo@" linkPolylineLvl="BBBBBBBBBBBBBBBB" linkSpeed="11.81" linkTravelTime="214" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616276" linkName="VWE S MP2.66 (Exit 2 Rockaway Blvd) - Belt Pkwy E 182nd St" linkBorough="Queens" linkOwner="NYC_DOT_LIC" linkPolyline="ifgwFhlmaMlCu@`Fo@dJMrSp@`PfDnCd@pCk@|B_D^}D_@yCuAoCmIuEsCmEs@sCc@_GYyLaAa^uDuaAKqMLyT\mJ`Dij@" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="11.18" linkTravelTime="983" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616272" linkName="VWE S MP4.63 (Exit 6 Jamaica Ave) - MP2.66 (Exit 2 Roackaway Blvd)" linkBorough="Queens" linkOwner="NYC_DOT_LIC" linkPolyline="culwF~gpaMzHqCjUaKlGgDnl@wXndA_b@bRaH" linkPolylineLvl="BBBBBBB" linkSpeed="26.72" linkTravelTime="249" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616259" linkName="VWE S MP6.39 (Exit 11 Jewel Ave) - MP4.63 (Exit 6 Jamaica Ave)" linkBorough="Queens" linkOwner="NYC_DOT_LIC" linkPolyline="otqwFbosaMlEuBbBmA~BsC~CuF`CqDxBcC|CgCbK{FnBg@bDYnCXvGb@lADvAA~AUhBm@zA{@vCsCzB_BtEkDzIuKxAiBnGcFbHuDpPaIlN_F" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="8.08" linkTravelTime="1066" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616241" linkName="VWE S MP8.65 (Exit 13 Northern Blvd) - MP6.39 (Exit 11 Jewel Ave)" linkBorough="Queens" linkOwner="NYC_DOT_LIC" linkPolyline="gmxwF|xtaMpFiCbAUdBOhBDrI\tAGbM{A`BYrBm@hSwLpDyBpBw@|A_@jBMrCLbEjA~BdBjCvBf@XnAlAbBhAvB|@xAZdBRtABjCItKoBpGmAvTcAfCc@|EeBt`@oP" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="14.91" linkTravelTime="429" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616213" linkName="WSE N ARDEN AVENUE - VICTORY BLVD" linkBorough="Staten Island" linkOwner="NYC_DOT_LIC" linkPolyline="wwvvFf{ycMnnA{PxFw@tKkApIBpD^`GpA~NbI`m@fm@" linkPolylineLvl="BBBBBBBBB" linkSpeed="8.08" linkTravelTime="942" linkStatus="0" linkTimeStamp="11/2/2016 12:30:30" />
<TrafficSpeedData linkId="4616214" linkName="WSE N BLOOMUINGDALE ROAD - ARDEN AVENUE" linkBorough="Staten Island" linkOwner="NYC_DOT_LIC" linkPolyline="s}pvFda{cMjFpGpCvExBrFlCdJ`Fb[`AzEjBbHtCxHtCfGfDbGlEvF~DlE|NvL" linkPolylineLvl="BBBBBBBBBBBBBB" linkSpeed="8.08" linkTravelTime="592" linkStatus="0" linkTimeStamp="11/2/2016 12:30:30" />
<TrafficSpeedData linkId="4329481" linkName="WSE N SOUTH AVENUE - 278 W BRUNSWICK AVENUE" linkBorough="Staten Island" linkOwner="PA - LINCOLN TUNNEL" linkPolyline="o~{vFdwvcMsK}FuHeCaHc@{G`@sCbBcBbDkBxE" linkPolylineLvl="BBBBBBBB" linkSpeed="6.21" linkTravelTime="2227" linkStatus="0" linkTimeStamp="12/3/2014 09:54:36" />
<TrafficSpeedData linkId="4616215" linkName="WSE N TYRELLAN AVENUE - BLOOMINGDALE ROAD" linkBorough="Staten Island" linkOwner="NYC_DOT_LIC" linkPolyline="adjvF|badMs@iYaBsPcEB_|@vDyLWeHg@mUeF}L}EuIaF" linkPolylineLvl="BBBBBBBBBB" linkSpeed="8.08" linkTravelTime="949" linkStatus="0" linkTimeStamp="11/2/2016 12:30:30" />
<TrafficSpeedData linkId="4616212" linkName="WSE N VICTORY BLVD - SOUTH AVENUE" linkBorough="Staten Island" linkOwner="NYC_DOT_LIC" linkPolyline="abyvFbxxcM~IxIrNvH~b@jLhGf@jBA" linkPolylineLvl="BBBBBB" linkSpeed="8.08" linkTravelTime="364" linkStatus="0" linkTimeStamp="11/2/2016 12:30:30" />
<TrafficSpeedData linkId="4616198" linkName="WSE N-SIE E SOUTH AVENUE - SOUTH AVENUE" linkBorough="Staten Island" linkOwner="NYC_DOT_LIC" linkPolyline="kx|vFjbucMi@rE?nEvBfOvDpHhDnD`KhG~}@zd@nNdKfM~M" linkPolylineLvl="BBBBBBBBBB" linkSpeed="8.08" linkTravelTime="735" linkStatus="0" linkTimeStamp="11/2/2016 12:30:30" />
<TrafficSpeedData linkId="4616202" linkName="WSE S ARDEN AVENUE - BLOOMINGDALE ROAD" linkBorough="Staten Island" linkOwner="NYC_DOT_LIC" linkPolyline="s~pvFjb{cMfGtHxCrFvB~FdBhGrFz\t@`DpC~JpCnHpBhE|DlGnEbGxDxDzMdL" linkPolylineLvl="BBBBBBBBBBBBBB" linkSpeed="57.17" linkTravelTime="82" linkStatus="0" linkTimeStamp="10/31/2016 11:15:35" />
<TrafficSpeedData linkId="4616203" linkName="WSE S BLLOMINGDALE ROAD - TYRELLAN AVENUE" linkBorough="Staten Island" linkOwner="NYC_DOT_LIC" linkPolyline="iejvF|badMWsKc@wDsAiCuBgAkKcCqJ{GyDm@i^`BgKOmQyAmKeCcLaE{FoCcHmE" linkPolylineLvl="BBBBBBBBBBBBBBB" linkSpeed="57.17" linkTravelTime="115" linkStatus="0" linkTimeStamp="10/31/2016 11:15:35" />
<TrafficSpeedData linkId="4616200" linkName="WSE S SOUTH AVENUE - VICTORY BOULEVARD" linkBorough="Staten Island" linkOwner="NYC_DOT_LIC" linkPolyline="yvvvFv|ycMoGG_PkDuYmIsGiDaIwGsCwC" linkPolylineLvl="BBBBBBB" linkSpeed="57.17" linkTravelTime="54" linkStatus="0" linkTimeStamp="10/31/2016 11:15:35" />
<TrafficSpeedData linkId="4329483" linkName="WSE S TYRELLAN AVENUE - 440 S FRANCIS STREET" linkBorough="Staten Island" linkOwner="NYC_DOT_LIC" linkPolyline="iijvFpzhdMxCoLnAoKfAuQz@yP~@_QCiNMmHc@gLuAmk@[uOa@qS_@eN_@sMc@wP" linkPolylineLvl="BBBBBBBBBBBBBBB" linkSpeed="26.72" linkTravelTime="278" linkStatus="0" linkTimeStamp="11/2/2016 09:26:57" />
<TrafficSpeedData linkId="4616201" linkName="WSE S VICTORY BOULEVARD - ARDEN AVENUE" linkBorough="Staten Island" linkOwner="NYC_DOT_LIC" linkPolyline="s~pvFjb{cMgn@in@cK{F}JwBwIUyGp@qFv@qG|@wkAvO" linkPolylineLvl="BBBBBBBBB" linkSpeed="57.17" linkTravelTime="136" linkStatus="0" linkTimeStamp="10/31/2016 11:15:35" />
<TrafficSpeedData linkId="4616335" linkName="West St N Whitehall - Watts St" linkBorough="Manhattan" linkOwner="NYC_DOT_LIC" linkPolyline="wnlwF~pvbMTrBYxDi@`DsA|BsBxAsDzA{Cf@iCDgCm@oCu@y@a@yFwAoImCwRcCwDgA{@i@}COiDaAsQiCwK}AqUiC" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBB" linkSpeed="8.7" linkTravelTime="866" linkStatus="0" linkTimeStamp="12/8/2015 15:24:35" />
<TrafficSpeedData linkId="4616343" linkName="West St S Battery Pl - BKN Bridge Manhattan Side" linkBorough="Manhattan" linkOwner="NYC_DOT_LIC" linkPolyline="ucmwFjkwbMxAEtAK|DkAlCuArAkAhAsB\sDL{Cc@aE{AuK_@sBwAyCyBoEeDoGeCoEiCyEoCaFcDwG}CcHu@mBgAuB" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBB" linkSpeed="19.26" linkTravelTime="300" linkStatus="0" linkTimeStamp="12/8/2015 15:24:35" />
<TrafficSpeedData linkId="4616327" linkName="West St S Battery Pl - FDR N Catherine Slip" linkBorough="Manhattan" linkOwner="NYC_DOT_LIC" linkPolyline="}emwF|jwbM|CF~CU~FoCzBqBj@kBVsCNoCg@wFaB_LiF{L}IkP}IkP}GyOeCkGq@qEa@qF" linkPolylineLvl="BBBBBBBBBBBBBBBBB" linkSpeed="13.05" linkTravelTime="105" linkStatus="0" linkTimeStamp="12/8/2015 15:24:35" />
<TrafficSpeedData linkId="4456494" linkName="West St S Spring St - BBT Manhattan Portal outbound" linkBorough="Manhattan" linkOwner="NYC_DOT_LIC" linkPolyline="wiqwFnhvbMvD^xb@lFxQvCrb@hHlLjChHnBPgBh@gA|@WzANnDv@|Cl@|ATvBT`E?fFKzD{@zDcAvC}@dD}@zFaBtF}AtF{ApH}DnIqEnOcI~McHxLeGlHcCjHeF" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="14.91" linkTravelTime="490" linkStatus="0" linkTimeStamp="11/14/2016 17:12:40" />
<TrafficSpeedData linkId="4616326" linkName="West St S Spring St - Battery Pl" linkBorough="Manhattan" linkOwner="NYC_DOT_LIC" linkPolyline="uiqwFphvbMjc@`F|r@pLjMfCbQlEdJz@" linkPolylineLvl="BBBBBB" linkSpeed="13.05" linkTravelTime="779" linkStatus="0" linkTimeStamp="12/8/2015 15:24:35" />
<TrafficSpeedData linkId="4616336" linkName="West St Watts St - 11th Ave Ganesvoort" linkBorough="Manhattan" linkOwner="NYC_DOT_LIC" linkPolyline="m}pwFfivbMmOwAiTiAaUeAyVm@oGP{Cu@uCwA" linkPolylineLvl="BBBBBBBB" linkSpeed="8.7" linkTravelTime="444" linkStatus="0" linkTimeStamp="12/8/2015 15:24:35" />
<TrafficSpeedData linkId="4620343" linkName="Westside Hwy N 57th St - GWB" linkBorough="Manhattan" linkOwner="NYC_DOT_LIC" linkPolyline="ydzwF|~rbMqAk@eQyKkUkOyHiFgGgFyPaLgJ{FgJ_D}IsCsGwCiHyEgDiCwDuDiJqLsBmBuAi@uFyAmLeDoCqAsHsEgRiMwLqIeU{MeIcGyDuBgF}BcBiAkBsA{CmCyGcHmC_CoFsEoEqDqJyGqHqFcN_MuKqJaCyAwCuAsHsBeOyCwJiBuCmAkH{GkDkCaDmBgBy@gDkAeJiAaK[cFq@yA_@oIoDiEiA" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="45.98" linkTravelTime="393" linkStatus="0" linkTimeStamp="11/2/2016 10:32:58" />
<TrafficSpeedData linkId="4616346" linkName="Westside Hwy S GWB - 57th St" linkBorough="Manhattan" linkOwner="NYC_DOT_LIC" linkPolyline="uoixFdjibMdDpAhDDnWk@rDJvD^hG|AzEpB~BzAbEfD|D|Dx@t@lClAbCh@bIzAzAb@jNrCpGvBjDrBjQvOlL|JpJxGvHlGnHtFlJfJhH~Gb@^r@b@hLhGfGjEtOvInUpOpSdNjIxEtAr@rRfGvCxAVNlCnC~EzFnCzCrBrBpEdDtIdFhEhBvCdA|ErAdHzB~A~@hDvBlBpAfC`BfC~A`EjCf@^dGjFpBzA~CtBhD`C`J~FdJ|FfIlFtCjBnBjA" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="13.05" linkTravelTime="1516" linkStatus="0" linkTimeStamp="11/2/2016 11:28:29" />
<TrafficSpeedData linkId="4456500" linkName="Whitestone Expwy N Exit 14 (Linden Pl) - BWB N Queens Anchorage" linkBorough="Queens" linkOwner="NYC_DOT_LIC" linkPolyline="kczwFdqsaMoHgNmBoCoDoDeIaFwPeIuLcFkEuAyE_AoXeD{EsBqCeBoA_@kCQeBJwCr@aA`@oXtOyUlN" linkPolylineLvl="BBBBBBBBBBBBBBBBBBB" linkSpeed="44.12" linkTravelTime="163" linkStatus="0" linkTimeStamp="11/14/2016 17:12:40" />
<TrafficSpeedData linkId="4616239" linkName="Whitestone Expwy S Exit 14 (Linden Pl) - VWE S MP8.65 (Exit 13 Northern Blvd)" linkBorough="Queens" linkOwner="NYC_DOT_LIC" linkPolyline="kdzwF`rsaMdFdKlEdGzIvHzHdEvAv@rBz@bATjAJdBAhAKjCu@" linkPolylineLvl="BBBBBBBBBBBB" linkSpeed="14.91" linkTravelTime="322" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4362252" linkName="CIP N LIE ramp - TNB" linkBorough="Queens" linkOwner="NYC-DOT-Region 10" linkPolyline="ar}wFzekaMDaEy@kJeA}LKkDV_O\iEr@{FzAiGtA}DnBsEdBkCxBmCjE_E|FwEzG_GhMyMzE}CfJmDnKmEtImFjG{FnLgOlCqCtDiCnI_DxQyE|CaBnGsGpBeD~A}DpFsV`CgG~BaEtFqGxAeBzBiFtA{Ft@oHS_CwAmDiBuDa@oA}OyZcAaDoA}EmBwHiBwEgHkMaBoDsAmEaBiHk@{E" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="11.18" linkTravelTime="1051" linkStatus="0" linkTimeStamp="8/5/2016 14:17:16" />
<TrafficSpeedData linkId="4616228" linkName="I-87 NYST S Exit 1 - MDE S Van Cortlandt Park" linkBorough="Bronx" linkOwner="NYC_DOT_LIC" linkPolyline="cppxFv}_bMoEgH_CqFeD{LsCqPqBeGeEaGeRiRoP{OuFeD}GaBso@}FsN}AsD_BcCqBiFaG" linkPolylineLvl="BBBBBBBBBBBBBBBB" linkSpeed="44.12" linkTravelTime="158" linkStatus="0" linkTimeStamp="3/21/2014 15:24:27" />
<TrafficSpeedData linkId="4456483" linkName="CIP N ramp to TNB - TNB Queens Anchorage" linkBorough="Queens" linkOwner="NYC_DOT_LIC" linkPolyline="qu}wFlkjaMXjGtAzJ@nB_@tC]~@s@lAuAlAuCbB??mAh@mD`A{Dh@kDJ}F?ePM" linkPolylineLvl="BBBBBBBBBBBBBBBB" linkSpeed="45.98" linkTravelTime="35" linkStatus="0" linkTimeStamp="11/14/2016 17:12:40" />
<TrafficSpeedData linkId="4616261" linkName="BE S Griswold - Castle Hill Avenue" linkBorough="Bronx" linkOwner="NYC_DOT_LIC" linkPolyline="ytexFj}vaMpAqGbBgHrAgGl@sF?oEa@cGoDu\e@cGAsEF}FMkBe@{Ci@}AyN}XqEcLyA}B_As@uA}@{AWiBEaBRoEdA}DZ" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="16.16" linkTravelTime="462" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616247" linkName="BE N Castle Hill Avenue - Griswold Ave" linkBorough="Bronx" linkOwner="NYC_DOT_LIC" linkPolyline="w`exF~xvaMmBaSkCiSw@iLScPW}Hy@eH_BmHcDeIaIaO{DwHyBiG_CsF_C{BmDuAgDIcC`@gDbAgCZ" linkPolylineLvl="BBBBBBBBBBBBBBBBBBB" linkSpeed="26.72" linkTravelTime="278" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
<TrafficSpeedData linkId="4616255" linkName="MDE N RFK Bridge - 142nd St" linkBorough="Bronx" linkOwner="NYC_DOT_LIC" linkPolyline="_mbxFnufbMnE~@xBP|BOpBeA|A}ArLaQjBgElFiQjHiVvFiPd@kBd@_EB{DQcBi@uB{@cCcEmL??wCcI_AyCgEwMo@wAa^{j@eGiJcAiAyB}Bya@gc@_A{@sFgJcC}CK_@cGm{@uAmS" linkPolylineLvl="BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB" linkSpeed="3.73" linkTravelTime="1039" linkStatus="0" linkTimeStamp="11/14/2016 17:13:15" />
</NYCDOT-TrafficSpeed>